# Generated by Django 3.2.8 on 2021-10-26 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.CharField(max_length=200, null=True, verbose_name='descrip ')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, null=True, verbose_name='Nombre ')),
                ('email', models.EmailField(max_length=60, null=True, verbose_name='Email ')),
                ('mensaje', models.TextField(max_length=100, null=True, verbose_name='Mensaje ')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoperfil', models.ImageField(null=True, upload_to='', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, null=True, verbose_name='Email ')),
                ('nombre', models.CharField(max_length=20, null=True, verbose_name='Nombre ')),
                ('contrasena', models.CharField(max_length=20, null=True, verbose_name='Contrasena ')),
            ],
        ),
        migrations.CreateModel(
            name='Publicar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, null=True, verbose_name='Titulo ')),
                ('foto', models.ImageField(null=True, upload_to='', verbose_name='image')),
                ('lead', models.TextField(max_length=1000, null=True, verbose_name='lead ')),
                ('noticia', models.TextField(max_length=2200, null=True, verbose_name='noticia ')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
